In [2]:
import numpy as np
import pandas as pd
from scipy.io import arff
import pandas as pd
import pytempo
import sys

In [3]:
train = arff.loadarff('Adiac_TRAIN.arff')
train = pd.DataFrame(train[0])
test = arff.loadarff('Adiac_TEST.arff')
test = pd.DataFrame(test[0])
print(train.info())
print(test.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 390 entries, 0 to 389
Columns: 177 entries, att1 to target
dtypes: float64(176), object(1)
memory usage: 539.4+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 391 entries, 0 to 390
Columns: 177 entries, att1 to target
dtypes: float64(176), object(1)
memory usage: 540.8+ KB
None


In [4]:
np_train=train.iloc[:,:-1].to_numpy()
np_train

array([[1.5980065, 1.5994389, 1.5705294, ..., 1.5641545, 1.5708545,
        1.5928905],
       [1.7011457, 1.670645 , 1.6188844, ..., 1.5197372, 1.6025179,
        1.6701904],
       [1.722342 , 1.6953288, 1.6569459, ..., 1.6418088, 1.6949728,
        1.7084884],
       ...,
       [2.5955985, 2.6250629, 2.4239586, ..., 2.1440004, 2.1288939,
        2.1176354],
       [1.6598998, 1.6441473, 1.5937788, ..., 1.5798671, 1.636902 ,
        1.6601968],
       [1.7266289, 1.7288809, 1.7116989, ..., 1.5963694, 1.6403326,
        1.6988142]])

In [5]:
np_train_label=train.iloc[:,-1].to_numpy()
np_train_label=np_train_label.astype(int)
np_train_label

array([22, 28, 21, 15,  2, 18, 21, 36, 11, 21, 29, 26,  1,  9, 17,  7, 36,
       25, 11, 10, 25, 14,  3,  4, 36,  4,  4, 12, 23, 23,  6, 22,  8, 25,
       21, 34, 33, 28,  1, 24,  2, 37, 32, 37, 12, 17,  6, 11,  4, 29, 20,
        2, 27, 17, 20, 32, 25, 30, 31, 34, 16, 32, 28, 23, 15, 20, 24, 11,
       35, 36, 26, 12, 18, 28,  2, 14,  7, 28, 34, 27, 31, 31, 35,  9, 19,
       36, 12, 10, 10,  7, 14, 15, 10, 15,  6,  4, 32, 17, 23, 33, 19, 33,
       18, 22, 34,  9, 10, 15, 32, 30, 10, 14,  1, 27, 16, 36, 24, 22, 32,
       15,  2,  4, 26, 27, 12, 16, 28, 24, 23, 37, 13,  4,  8, 14, 31, 24,
       29, 27, 35,  6,  2, 34,  1, 32,  6, 26, 33, 21,  4, 11,  8, 30,  7,
       17, 20, 16,  2, 11, 25,  5, 36, 13,  3, 12,  2, 18, 12, 37, 27, 28,
       24, 24, 11, 21, 20, 14, 28, 10, 22,  9, 12, 24,  6, 17,  9, 26, 27,
        5, 25, 19,  7, 14, 20, 19, 24,  7,  1, 31, 21, 22, 24, 30, 29,  8,
       15, 20, 37, 12, 18, 16, 17,  5, 33, 12, 14,  6, 28, 34, 14,  7,  6,
       32, 25, 16,  9, 37

In [16]:
np_test=test.iloc[:,:-1].to_numpy()
np_test

array([[1.374884 , 1.2894387, 1.2043045, ..., 1.6103982, 1.53924  ,
        1.4519241],
       [1.339994 , 1.2353184, 1.1320378, ..., 1.6572156, 1.5480958,
        1.4413616],
       [1.6741981, 1.6438445, 1.5707222, ..., 1.5604672, 1.6344822,
        1.6737078],
       ...,
       [1.6519997, 1.6967991, 1.7005604, ..., 1.499251 , 1.5557159,
        1.6203831],
       [1.3986733, 1.2933925, 1.1888369, ..., 1.6363385, 1.5626484,
        1.4605437],
       [1.7271724, 1.7283587, 1.6937594, ..., 1.6272951, 1.6753428,
        1.6989307]])

In [12]:
np_test_label=test.iloc[:,-1].to_numpy()
np_test_label=np_test_label.astype(int)
np_test_label

array([16, 36, 34, 22, 16, 31, 24,  2, 30, 14, 24, 14, 25, 18, 32, 28, 18,
       26, 31, 37, 10, 31, 21, 14, 34,  3,  2, 29, 32, 32,  5, 12, 20, 18,
       36, 35, 37, 20,  7, 11, 12, 12,  8,  6, 12, 15,  7, 20, 25, 16, 14,
       15, 13, 36, 31, 12, 25, 27, 20, 10, 18, 17, 13, 23,  2, 11, 24, 18,
        7, 12,  3, 12, 36,  2, 12, 21, 23,  5, 15,  2, 26,  6, 26, 10,  2,
       10, 22,  4, 22, 31, 29,  3, 18, 11, 25, 31,  5, 20, 28, 36,  6, 31,
       21, 24, 17, 29, 19, 15, 21, 26, 34, 29, 22, 21, 21,  1, 22,  3, 35,
        3, 19,  6, 37, 25,  5,  8,  5,  3, 28, 14, 15, 25, 34,  9, 11, 21,
       23, 15, 18, 36, 19, 11, 33, 20, 36, 16, 33, 37, 19, 17, 26, 34, 14,
       13, 19, 35, 16, 14, 37, 25,  5,  5, 17, 19, 27, 37, 13, 35,  4, 35,
       34, 28, 13,  3,  3, 21, 18,  2, 18, 36,  7,  3, 25,  3, 29,  4, 20,
        8, 13, 33, 35,  1, 34, 37, 25, 30,  1, 36,  8, 35, 24,  9, 26, 11,
       33, 26, 23, 36, 24,  3, 23,  5, 17, 21, 12, 22, 11, 17, 10,  8, 10,
        8, 21, 31, 30, 37

In [25]:
# Euclidean
def Euclidean():
    min_ed =sys.maxsize
    min_y = sys.maxsize
    result_ed=[]
    ed=[]
    for i in range(len(np_test)):
        q = np_test[i]
        for j in range(len(np_train)):
            c= np_train[j]
            v = np.sum(np.square(q - c))
            if(v<min_ed):
                min_ed = v
                min_y = np_train_label[j]
        result_ed.append(min_y)
    return result_ed

# DTW
def dtw():
    min_dtw =sys.maxsize
    min_y = sys.maxsize
    ud = pytempo.univariate.distances
    result=[]
    dtw=[]
    for i in range(len(np_test)):
        q = np_test[i]
        for j in range(len(np_train)):
            c= np_train[j]
            v = ud.dtw(q, c)
            if(v<min_dtw):
                min_dtw = v
                min_y = np_train_label[j]
        result.append(min_y)
        dtw.append(min_dtw)  
    return result

In [26]:
q1=0
q2=0
r1 = Euclidean()
r2 = dtw()
for i in range(len(np_test_label)):
    if r1[i]==np_test_label[i]:
        q1=q1+1
    if r2[i]==np_test_label[i]:
        q2=q2+1
a1 = q1/len(np_test_label)
a2 = q2/len(np_test_label)
print(f'Ed: {format(1-a1, ".4f")}')
print(f'Default Rate: {format(1-a2, ".4f")}')

Ed: 0.9565
Default Rate: 0.9642
