In [3]:
import numpy as np
import pandas as pd
from scipy.io import arff
import pandas as pd
import pytempo
import sys
import math

In [4]:
train = arff.loadarff('Computers_TRAIN.arff')
train = pd.DataFrame(train[0])
test = arff.loadarff('Computers_TEST.arff')
test = pd.DataFrame(test[0])
print(train.info())
print(test.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Columns: 721 entries, att1 to target
dtypes: float64(720), object(1)
memory usage: 1.4+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Columns: 721 entries, att1 to target
dtypes: float64(720), object(1)
memory usage: 1.4+ MB
None


In [5]:
np_train=train.iloc[:,:-1].to_numpy()
np_train

array([[-0.33503182, -0.33503182, -0.33503182, ..., -0.33503182,
        -0.33503182, -0.33503182],
       [-0.60252494, -0.60252494, -0.60252494, ..., -0.60252494,
        -0.60252494, -0.60252494],
       [-0.3202215 , -0.3202215 , -0.3202215 , ..., -0.3202215 ,
        -0.3202215 , -0.3202215 ],
       ...,
       [-0.14388754, -0.47382074, -0.14388754, ..., -0.47382074,
        -0.14388754, -0.47382074],
       [-0.41048285, -0.64030218, -0.41048285, ..., -0.64030218,
        -0.41048285, -0.64030218],
       [ 6.9858988 ,  6.9858988 ,  6.9858988 , ..., -0.40296684,
        -0.40296684, -0.40296684]])

In [6]:
np_train_label=train.iloc[:,-1].to_numpy()
np_train_label=np_train_label.astype(int)
np_train_label

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2])

In [7]:
np_test=test.iloc[:,:-1].to_numpy()
np_test

array([[-0.61463597, -0.61463597, -0.61463597, ..., -0.61463597,
        -0.61463597, -0.61463597],
       [-0.30610884, -0.30610884, -0.30610884, ..., -0.30610884,
        -0.30610884, -0.20633593],
       [ 1.4364003 ,  1.4364003 ,  1.4364003 , ..., -0.72557049,
        -0.72557049, -0.67643479],
       ...,
       [-0.37082887, -0.37082887, -0.37082887, ..., -0.37082887,
        -0.37082887, -0.37082887],
       [ 1.6489296 ,  1.1754268 ,  1.6489296 , ..., -0.71858431,
        -0.71858431, -0.71858431],
       [-0.43168071, -0.43168071, -0.43168071, ...,  1.899978  ,
         1.899978  ,  1.899978  ]])

In [8]:
np_test_label=test.iloc[:,-1].to_numpy()
np_test_label=np_test_label.astype(int)
np_test_label

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2])

In [9]:
# Euclidean
def Euclidean():
    min_ed =sys.maxsize
    min_y = sys.maxsize
    result_ed=[]
    ed=[]
    for i in range(len(np_test)):
        q = np_test[i]
        min_ed =sys.maxsize
        min_y = sys.maxsize
        for j in range(len(np_train)):
            c= np_train[j]
            v = np.linalg.norm(q - c)
            if(v<min_ed):
                min_ed = v
                min_y = np_train_label[j]
        result_ed.append(min_y)
    return result_ed

# DTW
def dtw():
    min_dtw =sys.maxsize
    min_y = sys.maxsize
    ud = pytempo.univariate.distances
    result=[]
    dtw=[]
    for i in range(len(np_test)):
        q = np_test[i]
        min_dtw =sys.maxsize
        min_y = sys.maxsize
        for j in range(len(np_train)):
            c= np_train[j]
            v = ud.dtw(q, c)
            if(v<min_dtw):
                min_dtw = v
                min_y = np_train_label[j]
        result.append(min_y)
        dtw.append(min_dtw)  
    return result
def cdtw(w):
    min_cdtw =sys.maxsize
    min_y = sys.maxsize
    result_cdtw=[]
    cdtw=[]
    L = 720
    for i in range(len(np_test)):
        q = np_test[i]
        min_cdtw =sys.maxsize
        min_y = sys.maxsize
        for j in range(len(np_train)):
            c= np_train[j]
            v = ud.cdtw(q, c, w*round(L/100))
            if(v<min_cdtw):
                min_cdtw = v
                min_y = np_train_label[j]
        result_cdtw.append(min_y)
        cdtw.append(min_cdtw) 
    return result_cdtw

In [10]:
q1=0
q2=0
q3=0
ud = pytempo.univariate.distances
r1 = Euclidean()
r2 = dtw()
r3 = cdtw(12)
for i in range(len(np_test_label)):
    if r1[i]==np_test_label[i]:
        q1=q1+1
    if r2[i]==np_test_label[i]:
        q2=q2+1
    if r3[i]==np_test_label[i]:
        q3=q3+1   
a1 = q1/len(np_test_label)
a2 = q2/len(np_test_label)
a3 = q3/len(np_test_label)
print(f'Ed: {format(1-a1, ".4f")}')
print(f'DTW(Learned w): {format(1-a3, ".4f")}')
print(f'DTW(w=100): {format(1-a2, ".4f")}')

Ed: 0.4240
DTW(Learned w): 0.3880
DTW(w=100): 0.3000
