In [1]:
import numpy as np
import pandas as pd
from scipy.io import arff
import pandas as pd
import pytempo
import sys
import math

In [2]:
train = arff.loadarff('CricketY_TRAIN.arff')
train = pd.DataFrame(train[0])
test = arff.loadarff('CricketY_TEST.arff')
test = pd.DataFrame(test[0])
print(train.info())
print(test.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 390 entries, 0 to 389
Columns: 301 entries, att1 to target
dtypes: float64(300), object(1)
memory usage: 917.2+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 390 entries, 0 to 389
Columns: 301 entries, att1 to target
dtypes: float64(300), object(1)
memory usage: 917.2+ KB
None


In [3]:
np_train=train.iloc[:,:-1].to_numpy()
np_train

array([[ 0.64856349,  0.61371976,  0.79789607, ...,  0.27722782,
         0.27049531,  0.26870697],
       [-0.33729635, -0.23942801, -0.33710738, ..., -0.31755228,
        -0.32053349, -0.32005493],
       [ 0.58008868,  0.4554952 ,  0.60869702, ...,  1.2063834 ,
         1.1014446 ,  1.0973218 ],
       ...,
       [ 0.42941819,  0.51020363,  0.4277726 , ...,  1.2200804 ,
         1.2146325 ,  1.2128421 ],
       [-0.60367946, -0.4538433 , -0.71057727, ..., -0.9851651 ,
        -0.98076995, -0.97583706],
       [-0.01107744, -0.11726703, -0.23208957, ...,  0.26705055,
         0.26616458,  0.50391719]])

In [4]:
np_train_label=train.iloc[:,-1].to_numpy()
np_train_label=np_train_label.astype(int)
np_train_label

array([ 2,  4,  3,  3,  5,  1,  8, 10,  4,  5, 10,  2,  9,  5,  5, 10,  7,
       11,  7,  5,  2,  3,  3,  7,  1,  9,  6,  8, 12,  4, 11, 10,  9,  7,
        5,  6, 11,  8,  8, 10, 10, 12,  7,  3,  4,  7,  1, 12, 11, 12, 12,
        9, 10,  4,  2,  5,  2,  7,  5,  7, 12,  4,  3, 12,  8,  3, 10,  4,
        7,  7,  1,  4, 11,  8,  6,  3,  6,  1,  5,  9, 10, 12, 11,  5,  9,
        5,  8, 11,  9, 12,  2,  5, 11, 10,  4,  4,  7, 10, 10,  9,  1,  6,
        5, 10,  8, 11, 12,  9,  5, 12,  1,  1, 12, 12,  5,  3,  2,  7,  9,
        7,  6,  3,  1, 11,  2,  2, 10, 11,  8, 11,  5,  8,  8, 12,  2,  3,
        4, 10,  3,  7,  9,  6,  7,  3,  9,  9,  4,  3, 12,  4,  6, 10,  1,
        6,  1,  1,  1,  4,  5,  5, 12, 11, 12, 10,  1,  3,  7, 12,  5,  9,
        2,  6, 10, 12,  6, 11,  1,  1,  6,  6,  5, 10, 10,  2,  4,  5, 11,
       10, 12,  3,  4,  3,  1,  4,  5,  7,  9,  4,  8,  3,  7,  8,  9, 12,
        8,  7,  1, 10,  9,  6,  5,  2,  4, 10,  7,  5,  1,  2,  7,  6,  8,
       11,  4,  2,  5, 11

In [5]:
np_test=test.iloc[:,:-1].to_numpy()
np_test

array([[-0.11105748, -0.09022612, -0.01983751, ..., -0.52912551,
        -0.52302749, -0.52768319],
       [ 0.60310085,  0.44417446,  0.42087495, ...,  0.1473066 ,
         0.1554887 ,  0.15103478],
       [ 0.5028739 ,  0.51713595,  0.56797241, ...,  0.5376856 ,
         0.55332614,  0.54481222],
       ...,
       [ 0.11665757, -0.23675922, -0.11618954, ..., -0.20370227,
         0.14814326,  0.14307585],
       [-0.30038609, -0.31129898, -0.23701196, ..., -0.28414469,
        -0.4141128 , -0.41894275],
       [-0.1846542 , -0.29486701, -0.18302842, ..., -0.28816946,
        -0.28222449, -0.28546063]])

In [6]:
np_test_label=test.iloc[:,-1].to_numpy()
np_test_label=np_test_label.astype(int)
np_test_label

array([ 7,  9, 12,  4,  6, 11,  2,  9,  1, 11,  3,  5,  5,  9, 12,  5,  5,
        6,  1,  6,  4,  4,  7,  9,  5,  3,  3,  9, 11,  4,  8, 10, 10,  1,
        4,  5, 12,  6,  5,  9,  7, 10,  3, 11,  9,  5, 11,  8, 11,  6, 12,
        3,  3, 12,  7,  9,  5, 10,  4, 12, 11, 11,  8,  2,  8,  9,  2,  2,
        5,  5, 11,  6,  9,  1,  7,  4, 12, 11,  2, 12, 12,  8,  3,  7,  5,
        6,  2, 11,  4,  7,  4,  6, 11,  4,  3, 11,  2,  4,  1,  9,  8, 10,
       11,  5, 10, 12, 12,  2,  2,  8,  2,  8,  4,  2,  7,  1,  7, 10,  3,
        7,  1,  7, 11,  6, 12, 12,  4, 11,  9,  7,  2,  3,  6,  2,  5,  5,
        8,  8,  6,  5,  9,  4,  5, 12, 11,  6,  6,  2,  4,  8, 10, 11,  1,
        4,  4,  8,  6,  7,  9,  7,  2, 10, 10,  8,  3,  6,  8, 11,  9,  7,
        9, 11,  7,  1, 11, 10,  5,  1,  1,  2,  9, 12,  8, 12, 10,  1,  4,
       10,  2,  3,  8,  2,  2, 10,  6, 11,  8,  2, 10,  9,  5,  8, 10,  7,
        8,  3,  1,  8,  9,  7,  1, 11,  6,  7, 12,  5,  8, 12, 11,  8, 10,
        8,  7,  4,  3, 10

In [7]:

# Euclidean
def Euclidean():
    min_ed =sys.maxsize
    min_y = sys.maxsize
    result_ed=[]
    ed=[]
    for i in range(len(np_test)):
        q = np_test[i]
        min_ed =sys.maxsize
        min_y = sys.maxsize
        for j in range(len(np_train)):
            c= np_train[j]
            v = np.linalg.norm(q - c)
            if(v<min_ed):
                min_ed = v
                min_y = np_train_label[j]
        result_ed.append(min_y)
    return result_ed

# DTW
def dtw():
    min_dtw =sys.maxsize
    min_y = sys.maxsize
    ud = pytempo.univariate.distances
    result=[]
    dtw=[]
    for i in range(len(np_test)):
        q = np_test[i]
        min_dtw =sys.maxsize
        min_y = sys.maxsize
        for j in range(len(np_train)):
            c= np_train[j]
            v = ud.dtw(q, c)
            if(v<min_dtw):
                min_dtw = v
                min_y = np_train_label[j]
        result.append(min_y)
        dtw.append(min_dtw)  
    return result
def cdtw(w):
    min_cdtw =sys.maxsize
    min_y = sys.maxsize
    result_cdtw=[]
    cdtw=[]
    L = 300
    for i in range(len(np_test)):
        q = np_test[i]
        min_cdtw =sys.maxsize
        min_y = sys.maxsize
        for j in range(len(np_train)):
            c= np_train[j]
            v = ud.cdtw(q, c, round(w*(L/100)))
            if(v<min_cdtw):
                min_cdtw = v
                min_y = np_train_label[j]
        result_cdtw.append(min_y)
        cdtw.append(min_cdtw) 
    return result_cdtw

In [8]:
q1=0
q2=0
q3=0
ud = pytempo.univariate.distances
r1 = Euclidean()
r2 = dtw()
r3 = cdtw(17)
for i in range(len(np_test_label)):
    if r1[i]==np_test_label[i]:
        q1=q1+1
    if r2[i]==np_test_label[i]:
        q2=q2+1
    if r3[i]==np_test_label[i]:
        q3=q3+1   
a1 = q1/len(np_test_label)
a2 = q2/len(np_test_label)
a3 = q3/len(np_test_label)
print(f'Ed: {format(1-a1, ".4f")}')
print(f'DTW(Learned w): {format(1-a3, ".4f")}')
print(f'DTW(w=100): {format(1-a2, ".4f")}')

Ed: 0.4333
DTW(Learned w): 0.2385
DTW(w=100): 0.2564
